import { Language, FieldWorkData, BreedAnalyticsData, SchemeData } from './types';

export const LANGUAGES = [
  { code: Language.EN, name: 'English' },
  { code: Language.HI, name: 'हिन्दी (Hindi)' },
  { code: Language.MR, name: 'मराठी (Marathi)' },
  { code: Language.GU, name: 'ગુજરાતી (Gujarati)' },
  { code: Language.TE, name: 'తెలుగు (Telugu)' },
  { code: Language.ML, name: 'മലയാളം (Malayalam)' },
  { code: Language.TA, name: 'தமிழ் (Tamil)' },
  { code: Language.KN, name: 'ಕನ್ನಡ (Kannada)' },
];

const englishTexts = {
  // General & Identifier
  title: 'Pashu Pehchan',
  subtitle: 'AI Cattle & Buffalo Breed Identifier',
  uploadTitle: 'Upload an Image',
  uploadSubtitle: 'Upload a clear photo of a single cow or buffalo to identify its breed.',
  uploadButton: 'Select Image',
  captureButton: 'Capture from Camera',
  orText: 'or',
  uploading: 'Uploading...',
  analyzing: 'Analyzing your champion...',
  identifying: 'Identifying the breed...',
  errorTitle: 'Analysis Failed',
  errorText: 'Sorry, we couldn\'t analyze the image. It might not be a clear photo of a cow or buffalo. Please try another one.',
  tryAgain: 'Try Again',
  confirmedTitle: 'Breed Identified!',
  confirmedText: 'This animal has been identified as:',
  resultsIntro: (species: string, breedName: string) => `Analysis complete! It looks like a ${species.toLowerCase()}. The breed is ${breedName}.`,
  uploadAnother: 'Upload Another',
  registerBreed: 'Register Breed',
  
  // Sidebar
  navIdentifier: 'Breed Identifier',
  navFieldWorker: 'Field Worker',
  navAnalytics: 'Breed Analytics',
  navSchemes: 'Schemes',
  navProfile: 'Profile',

  // Field Worker View
  fieldWorkerTitle: 'Field Worker Dashboard',
  totalAnalyzed: 'Total Breeds Analyzed',
  recentActivity: 'Recent Activity',
  breedDistribution: 'Breed Distribution',

  // Breed Analytics View
  analyticsTitle: 'Breed Analytics',
  searchPlaceholder: 'Search by breed name...',
  noResults: 'No breeds found matching your search.',
  milkQuality: 'Milk Quality',
  fatContent: 'Fat',
  proteinContent: 'Protein',
  primaryLocation: 'Primary Location',
  qualityRanking: 'Quality Ranking',
  milkCapacity: 'Milk Capacity',
  breedDetails: 'Breed Details',
  suitability: 'Suitability',
  monthlyExpense: 'Monthly Expense',
  breedingSeason: 'Breeding Season',
  matingSuggestions: 'Mating Suggestions',

  // Schemes View
  schemesTitle: 'Government Schemes',
  eligibility: 'Eligibility',
  learnMore: 'Learn More',

  // Profile View
  profileTitle: 'Profile & Settings',
  appearanceTitle: 'Appearance',
  themeLabel: 'Choose a theme to display the app.',
  themeLight: 'Light',
  themeDark: 'Dark',
  themeSystem: 'System',
  languageTitle: 'Language',
  languageLabel: 'Select your preferred language.',
  accessibilityTitle: 'Accessibility',
  voiceGuidanceTitle: 'Voice Guidance',
  voiceGuidanceLabel: 'Enable voice-guided instructions and results.',
  otherSettingsTitle: 'Other Settings',
  notificationsLabel: 'Enable Push Notifications',
  dataSyncLabel: 'Sync Data Now',
  feedbackTitle: 'Feedback & Support',
  feedbackDescription: 'Have a suggestion or found a bug? Let us know.',
  feedbackPlaceholder: 'Type your feedback here...',
  submitFeedback: 'Submit Feedback',
  submitting: 'Submitting',
  feedbackSubmitted: 'Submitted!',
  feedbackSuccessText: 'Thank you for your feedback!',
  logout: 'Logout',

  // Registration Form
  registrationFormTitle: 'Register Your Animal',
  ownerNameLabel: 'Owner Name',
  ownerContactLabel: 'Owner Contact',
  animalTypeLabel: 'Animal Type',
  submitRegistration: 'Submit Registration',
  cancel: 'Cancel',
  registering: 'Registering...',
  registrationSuccessTitle: 'Registration Successful!',
  registrationSuccessText: 'Your animal has been successfully registered with the BPA platform.',
  close: 'Close',

  // Auth
  authTitle: 'Welcome to Pashu Pehchan',
  authSubtitle: 'Sign in or create an account to continue',
  authSendOtp: 'Send OTP',
  authVerifyOtp: 'Verify OTP',
  authPhonePlaceholder: 'Phone Number',
  authNamePlaceholder: 'Your Name',
  authContinue: 'Continue',
  authOtpInfo: 'For demo, use OTP:',
  authChangePhone: 'Change phone number',
  authInvalidPhone: 'Please enter a valid 10-digit phone number.',
  authInvalidName: 'Please enter your name.',
  authInvalidOtp: 'Invalid OTP. Please try again.',
};

const hindiTexts = {
    // General & Identifier
    title: 'पशु पहचान',
    subtitle: 'एआई मवेशी और भैंस नस्ल पहचानकर्ता',
    uploadTitle: 'एक छवि अपलोड करें',
    uploadSubtitle: 'नस्ल की पहचान के लिए एक गाय या भैंस की स्पष्ट तस्वीर अपलोड करें।',
    uploadButton: 'छवि चुनें',
    captureButton: 'कैमरे से तस्वीर लें',
    orText: 'या',
    uploading: 'अपलोड हो रहा है...',
    analyzing: 'आपके चैंपियन का विश्लेषण किया जा रहा है...',
    identifying: 'नस्ल की पहचान की जा रही है...',
    errorTitle: 'विश्लेषण विफल',
    errorText: 'क्षमा करें, हम छवि का विश्लेषण नहीं कर सके। यह गाय या भैंस की स्पष्ट तस्वीर नहीं हो सकती है। कृपया दूसरी कोशिश करें।',
    tryAgain: 'पुनः प्रयास करें',
    confirmedTitle: 'नस्ल की पहचान हो गई!',
    confirmedText: 'इस जानवर की पहचान इस रूप में की गई है:',
    resultsIntro: (species: string, breedName: string) => `विश्लेषण पूरा! ऐसा लगता है कि यह एक ${species === 'COW' ? 'गाय' : 'भैंस'} है। नस्ल ${breedName} है।`,
    uploadAnother: 'दूसरी अपलोड करें',
    registerBreed: 'नस्ल दर्ज करें',

    // Sidebar
    navIdentifier: 'नस्ल पहचानकर्ता',
    navFieldWorker: 'फील्ड वर्कर',
    navAnalytics: 'नस्ल एनालिटिक्स',
    navSchemes: 'योजनाएं',
    navProfile: 'प्रोफ़ाइल',

    // Field Worker View
    fieldWorkerTitle: 'फील्ड वर्कर डैशबोर्ड',
    totalAnalyzed: 'कुल नस्लों का विश्लेषण किया गया',
    recentActivity: 'हाल की गतिविधि',
    breedDistribution: 'नस्ल वितरण',

    // Breed Analytics View
    analyticsTitle: 'नस्ल एनालिटिक्स',
    searchPlaceholder: 'नस्ल के नाम से खोजें...',
    noResults: 'आपकी खोज से मेल खाने वाली कोई नस्ल नहीं मिली।',
    milkQuality: 'दूध की गुणवत्ता',
    fatContent: 'वसा',
    proteinContent: 'प्रोटीन',
    primaryLocation: 'प्राथमिक स्थान',
    qualityRanking: 'गुणवत्ता रैंकिंग',
    milkCapacity: 'दूध क्षमता',
    breedDetails: 'नस्ल विवरण',
    suitability: 'उपयुक्तता',
    monthlyExpense: 'मासिक खर्च',
    breedingSeason: 'प्रजनन ऋतु',
    matingSuggestions: 'संभोग सुझाव',

    // Schemes View
    schemesTitle: 'सरकारी योजनाएं',
    eligibility: 'पात्रता',
    learnMore: 'और जानें',

    // Profile View
    profileTitle: 'प्रोफ़ाइल और सेटिंग्स',
    appearanceTitle: 'दिखावट',
    themeLabel: 'ऐप प्रदर्शित करने के लिए एक थीम चुनें।',
    themeLight: 'लाइट',
    themeDark: 'डार्क',
    themeSystem: 'सिस्टम',
    languageTitle: 'भाषा',
    languageLabel: 'अपनी पसंदीदा भाषा चुनें।',
    accessibilityTitle: 'अभिगम्यता',
    voiceGuidanceTitle: 'आवाज़ मार्गदर्शन',
    voiceGuidanceLabel: 'आवाज़-निर्देशित निर्देशों और परिणामों को सक्षम करें।',
    otherSettingsTitle: 'अन्य सेटिंग्स',
    notificationsLabel: 'पुश सूचनाएं सक्षम करें',
    dataSyncLabel: 'अभी डेटा सिंक करें',
    feedbackTitle: 'प्रतिक्रिया और सहायता',
    feedbackDescription: 'कोई सुझाव है या कोई बग मिला? हमें बताएं।',
    feedbackPlaceholder: 'अपनी प्रतिक्रिया यहां टाइप करें...',
    submitFeedback: 'प्रतिक्रिया भेजें',
    submitting: 'भेजा जा रहा है',
    feedbackSubmitted: 'भेज दिया गया!',
    feedbackSuccessText: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    logout: 'लॉग आउट',
    
    // Registration Form
    registrationFormTitle: 'अपने पशु को पंजीकृत करें',
    ownerNameLabel: 'मालिक का नाम',
    ownerContactLabel: 'मालिक का संपर्क',
    animalTypeLabel: 'पशु का प्रकार',
    submitRegistration: 'पंजीकरण जमा करें',
    cancel: 'रद्द करें',
    registering: 'पंजीकरण हो रहा है...',
    registrationSuccessTitle: 'पंजीकरण सफल!',
    registrationSuccessText: 'आपके पशु को बीपीए प्लेटफॉर्म पर सफलतापूर्वक पंजीकृत कर दिया गया है।',
    close: 'बंद करें',

    // Auth
    authTitle: 'पशु पहचान में आपका स्वागत है',
    authSubtitle: 'जारी रखने के लिए साइन इन करें या खाता बनाएं',
    authSendOtp: 'ओटीपी भेजें',
    authVerifyOtp: 'ओटीपी सत्यापित करें',
    authPhonePlaceholder: 'फ़ोन नंबर',
    authNamePlaceholder: 'आपका नाम',
    authContinue: 'जारी रखें',
    authOtpInfo: 'डेमो के लिए, ओटीपी का उपयोग करें:',
    authChangePhone: 'फ़ोन नंबर बदलें',
    authInvalidPhone: 'कृपया एक मान्य 10-अंकीय फ़ोन नंबर दर्ज करें।',
    authInvalidName: 'कृपया अपना नाम दर्ज करें।',
    authInvalidOtp: 'अमान्य ओटीपी। कृपया पुन: प्रयास करें।',
};

const marathiTexts = {
    title: "पशु ओळख",
    subtitle: "एआय गुरे आणि म्हैस जात ओळखकर्ता",
    uploadTitle: "एक प्रतिमा अपलोड करा",
    uploadSubtitle: "जातीची ओळख पटवण्यासाठी गाय किंवा म्हशीचा स्पष्ट फोटो अपलोड करा.",
    uploadButton: "प्रतिमा निवडा",
    captureButton: "कॅमेऱ्यातून कॅप्चर करा",
    orText: "किंवा",
    uploading: "अपलोड करत आहे...",
    analyzing: "तुमच्या चॅम्पियनचे विश्लेषण करत आहे...",
    identifying: "जातीची ओळख पटवत आहे...",
    errorTitle: "विश्लेषण अयशस्वी",
    errorText: "क्षमस्व, आम्हाला प्रतिमेचे विश्लेषण करता आले नाही. तो गाय किंवा म्हशीचा स्पष्ट फोटो नसू शकतो. कृपया दुसरा प्रयत्न करा.",
    tryAgain: "पुन्हा प्रयत्न करा",
    confirmedTitle: "जात ओळखली!",
    confirmedText: "या प्राण्याची ओळख अशी आहे:",
    resultsIntro: (species: string, breedName: string) => `विश्लेषण पूर्ण झाले! हे ${species.toLowerCase() === 'cow' ? 'गाय' : 'म्हैस'} सारखे दिसते. जात ${breedName} आहे.`,
    uploadAnother: "दुसरा अपलोड करा",
    registerBreed: "जात नोंदवा",
    navIdentifier: "जात ओळखकर्ता",
    navFieldWorker: "फील्ड वर्कर",
    navAnalytics: "जात विश्लेषण",
    navSchemes: "योजना",
    navProfile: "प्रोफाइल",
    fieldWorkerTitle: "फील्ड वर्कर डॅशबोर्ड",
    totalAnalyzed: "एकूण जातींचे विश्लेषण केले",
    recentActivity: "अलीकडील क्रियाकलाप",
    breedDistribution: 'जात वितरण',
    analyticsTitle: "जात विश्लेषण",
    searchPlaceholder: "जातीच्या नावाने शोधा...",
    noResults: "तुमच्या शोधाशी जुळणारी कोणतीही जात आढळली नाही.",
    milkQuality: "दुधाची गुणवत्ता",
    fatContent: "चरबी",
    proteinContent: "प्रोटीन",
    primaryLocation: "प्राथमिक स्थान",
    qualityRanking: "गुणवत्ता रँकिंग",
    milkCapacity: "दूध क्षमता",
    breedDetails: "जातीचे तपशील",
    suitability: "योग्यता",
    monthlyExpense: "मासिक खर्च",
    breedingSeason: "प्रजनन हंगाम",
    matingSuggestions: "संभोग सूचना",
    schemesTitle: "सरकारी योजना",
    eligibility: "पात्रता",
    learnMore: "अधिक जाणून घ्या",
    profileTitle: "प्रोफाइल आणि सेटिंग्ज",
    appearanceTitle: "स्वरूप",
    themeLabel: "अ‍ॅप प्रदर्शित करण्यासाठी एक थीम निवडा.",
    themeLight: "लाइट",
    themeDark: "डार्क",
    themeSystem: "सिस्टम",
    languageTitle: "भाषा",
    languageLabel: "तुमची पसंतीची भाषा निवडा.",
    accessibilityTitle: "प्रवेशयोग्यता",
    voiceGuidanceTitle: "आवाज मार्गदर्शन",
    voiceGuidanceLabel: "आवाज-मार्गदर्शित सूचना आणि परिणाम सक्षम करा.",
    otherSettingsTitle: "इतर सेटिंग्ज",
    notificationsLabel: "पुश सूचना सक्षम करा",
    dataSyncLabel: "आता डेटा सिंक करा",
    feedbackTitle: 'अभिप्राय आणि समर्थन',
    feedbackDescription: 'काही सूचना आहे किंवा बग सापडला? आम्हाला कळवा.',
    feedbackPlaceholder: 'तुमचा अभिप्राय येथे टाइप करा...',
    submitFeedback: 'अभिप्राय सबमिट करा',
    submitting: 'सबमिट करत आहे',
    feedbackSubmitted: 'सबमिट केले!',
    feedbackSuccessText: 'तुमच्या अभिप्रायाबद्दल धन्यवाद!',
    logout: 'लॉगआउट करा',
    registrationFormTitle: 'तुमच्या प्राण्याची नोंदणी करा',
    ownerNameLabel: 'मालकाचे नाव',
    ownerContactLabel: 'मालकाचा संपर्क',
    animalTypeLabel: 'प्राण्याचा प्रकार',
    submitRegistration: 'नोंदणी सबमिट करा',
    cancel: 'रद्द करा',
    registering: 'नोंदणी करत आहे...',
    registrationSuccessTitle: 'नोंदणी यशस्वी!',
    registrationSuccessText: 'तुमचा प्राणी BPA प्लॅटफॉर्मवर यशस्वीरित्या नोंदणीकृत झाला आहे.',
    close: 'बंद करा',
    authTitle: 'पशु ओळख मध्ये आपले स्वागत आहे',
    authSubtitle: 'सुरू ठेवण्यासाठी साइन इन करा किंवा खाते तयार करा',
    authSendOtp: 'ओटीपी पाठवा',
    authVerifyOtp: 'ओटीपी सत्यापित करा',
    authPhonePlaceholder: 'फोन नंबर',
    authNamePlaceholder: 'तुमचे नाव',
    authContinue: 'पुढे जा',
    authOtpInfo: 'डेमोसाठी, ओटीपी वापरा:',
    authChangePhone: 'फोन नंबर बदला',
    authInvalidPhone: 'कृपया वैध १०-अंकी फोन नंबर प्रविष्ट करा.',
    authInvalidName: 'कृपया तुमचे नाव टाका.',
    authInvalidOtp: 'अवैध ओटीपी. कृपया पुन्हा प्रयत्न करा.',
};

const gujaratiTexts = {
    title: "પશુ પહચાન",
    subtitle: "AI ઢોર અને ભેંસની જાતિ ઓળખનાર",
    uploadTitle: "એક છબી અપલોડ કરો",
    uploadSubtitle: "જાતિ ઓળખવા માટે ગાય અથવા ભેંસનો સ્પષ્ટ ફોટો અપલોડ કરો.",
    uploadButton: "છબી પસંદ કરો",
    captureButton: "કેમેરાથી કેપ્ચર કરો",
    orText: "અથવા",
    uploading: "અપલોડ કરી રહ્યું છે...",
    analyzing: "તમારા ચેમ્પિયનનું વિશ્લેષણ કરી રહ્યું છે...",
    identifying: "જાતિની ઓળખ કરી રહ્યું છે...",
    errorTitle: "વિશ્લેષણ નિષ્ફળ",
    errorText: "માફ કરશો, અમે છબીનું વિશ્લેષણ કરી શક્યા નથી. તે ગાય અથવા ભેંસનો સ્પષ્ટ ફોટો ન હોઈ શકે. કૃપા કરીને બીજો પ્રયાસ કરો.",
    tryAgain: "ફરીથી પ્રયત્ન કરો",
    confirmedTitle: "જાતિ ઓળખાઈ!",
    confirmedText: "આ પ્રાણીની ઓળખ આ પ્રમાણે છે:",
    resultsIntro: (species: string, breedName: string) => `વિશ્લેષણ પૂર્ણ થયું! તે ${species.toLowerCase() === 'cow' ? 'ગાય' : 'ભેંસ'} જેવું લાગે છે. જાતિ ${breedName} છે.`,
    uploadAnother: "બીજું અપલોડ કરો",
    registerBreed: "જાતિની નોંધણી કરો",
    navIdentifier: "જાતિ ઓળખનાર",
    navFieldWorker: "ફિલ્ડ વર્કર",
    navAnalytics: "જાતિ વિશ્લેષણ",
    navSchemes: "યોજનાઓ",
    navProfile: "પ્રોફાઇલ",
    fieldWorkerTitle: "ફિલ્ડ વર્કર ડેશબોર્ડ",
    totalAnalyzed: "કુલ જાતિઓનું વિશ્લેષણ થયું",
    recentActivity: "તાજેતરની પ્રવૃત્તિ",
    breedDistribution: 'જાતિનું વિતરણ',
    analyticsTitle: "જાતિ વિશ્લેષણ",
    searchPlaceholder: "જાતિના નામ દ્વારા શોધો...",
    noResults: "તમારી શોધ સાથે મેળ ખાતી કોઈ જાતિ મળી નથી.",
    milkQuality: "દૂધની ગુણવત્તા",
    fatContent: "ચરબી",
    proteinContent: "પ્રોટીન",
    primaryLocation: "પ્રાથમિક સ્થાન",
    qualityRanking: "ગુણવત્તા રેન્કિંગ",
    milkCapacity: "દૂધની ક્ષમતા",
    breedDetails: "જાતિની વિગતો",
    suitability: "યોગ્યતા",
    monthlyExpense: "માસિક ખર્ચ",
    breedingSeason: "પ્રજનન મોસમ",
    matingSuggestions: "સમાગમ સૂચનો",
    schemesTitle: "સરકારી યોજનાઓ",
    eligibility: "પાત્રતા",
    learnMore: "વધુ જાણો",
    profileTitle: "પ્રોફાઇલ અને સેટિંગ્સ",
    appearanceTitle: "દેખાવ",
    themeLabel: "એપ પ્રદર્શિત કરવા માટે એક થીમ પસંદ કરો.",
    themeLight: "લાઇટ",
    themeDark: "ડાર્ક",
    themeSystem: "સિસ્ટમ",
    languageTitle: "ભાષા",
    languageLabel: "તમારી પસંદગીની ભાષા પસંદ કરો.",
    accessibilityTitle: "ઍક્સેસિબિલિટી",
    voiceGuidanceTitle: "અવાજ માર્ગદર્શન",
    voiceGuidanceLabel: "અવાજ-માર્ગદર્શિત સૂચનાઓ અને પરિણામો સક્ષમ કરો.",
    otherSettingsTitle: "અન્ય સેટિંગ્સ",
    notificationsLabel: "પુશ સૂચનાઓ સક્ષમ કરો.",
    dataSyncLabel: "હવે ડેટા સિંક કરો",
    feedbackTitle: 'પ્રતિસાદ અને સમર્થન',
    feedbackDescription: 'કોઈ સૂચન છે કે બગ મળ્યો? અમને જણાવો.',
    feedbackPlaceholder: 'તમારો પ્રતિસાદ અહીં લખો...',
    submitFeedback: 'પ્રતિસાદ સબમિટ કરો',
    submitting: 'સબમિટ કરી રહ્યું છે',
    feedbackSubmitted: 'સબમિટ કર્યું!',
    feedbackSuccessText: 'તમારા પ્રતિસાદ બદલ આભાર!',
    logout: 'લૉગઆઉટ કરો',
    registrationFormTitle: 'તમારા પશુની નોંધણી કરો',
    ownerNameLabel: 'માલિકનું નામ',
    ownerContactLabel: 'માલિકનો સંપર્ક',
    animalTypeLabel: 'પશુનો પ્રકાર',
    submitRegistration: 'નોંધણી સબમિટ કરો',
    cancel: 'રદ કરો',
    registering: 'નોંધણી કરી રહ્યું છે...',
    registrationSuccessTitle: 'નોંધણી સફળ!',
    registrationSuccessText: 'તમારું પશુ BPA પ્લેટફોર્મ પર સફળતાપૂર્વક નોંધાયેલું છે.',
    close: 'બંધ કરો',
    authTitle: 'પશુ પહચાનમાં આપનું સ્વાગત છે',
    authSubtitle: 'ચાલુ રાખવા માટે સાઇન ઇન કરો અથવા એકાઉન્ટ બનાવો',
    authSendOtp: 'OTP મોકલો',
    authVerifyOtp: 'OTP ચકાસો',
    authPhonePlaceholder: 'ફોન નંબર',
    authNamePlaceholder: 'તમારું નામ',
    authContinue: 'આગળ વધો',
    authOtpInfo: 'ડેમો માટે, OTP નો ઉપયોગ કરો:',
    authChangePhone: 'ફોન નંબર બદલો',
    authInvalidPhone: 'કૃપા કરીને માન્ય ૧૦-અંકનો ફોન નંબર દાખલ કરો.',
    authInvalidName: 'કૃપા કરીને તમારું નામ દાખલ કરો.',
    authInvalidOtp: 'અમાન્ય OTP. કૃપા કરીને ફરી પ્રયાસ કરો.',
};

const teluguTexts = {
    title: "పశు పెహచాన్",
    subtitle: "AI పశువులు మరియు గేదె జాతి ఐడెంటిఫైయర్",
    uploadTitle: "ఒక చిత్రాన్ని అప్‌లోడ్ చేయండి",
    uploadSubtitle: "దాని జాతిని గుర్తించడానికి ఒక ఆవు లేదా గేదె యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి.",
    uploadButton: "చిత్రాన్ని ఎంచుకోండి",
    captureButton: "కెమెరా నుండి క్యాప్చర్ చేయండి",
    orText: "లేదా",
    uploading: "అప్‌లోడ్ చేస్తోంది...",
    analyzing: "మీ ఛాంపియన్‌ను విశ్లేషిస్తోంది...",
    identifying: "జాతిని గుర్తిస్తోంది...",
    errorTitle: "విశ్లేషణ విఫలమైంది",
    errorText: "క్షమించండి, మేము చిత్రాన్ని విశ్లేషించలేకపోయాము. ఇది ఆవు లేదా గేదె యొక్క స్పష్టమైన ఫోటో కాకపోవచ్చు. దయచేసి మరొకదాన్ని ప్రయత్నించండి.",
    tryAgain: "మళ్లీ ప్రయత్నించండి",
    confirmedTitle: "జాతి గుర్తించబడింది!",
    confirmedText: "ఈ జంతువు ఇలా గుర్తించబడింది:",
    resultsIntro: (species: string, breedName: string) => `విశ్లేషణ పూర్తయింది! ఇది ${species.toLowerCase() === 'cow' ? 'ఆవు' : 'గేదె'} లాగా ఉంది. జాతి ${breedName}.`,
    uploadAnother: "మరొకటి అప్‌లోడ్ చేయండి",
    registerBreed: "జాతిని నమోదు చేయండి",
    navIdentifier: "జాతి ఐడెంటిఫైయర్",
    navFieldWorker: "ఫీల్డ్ వర్కర్",
    navAnalytics: "జాతి విశ్లేషణలు",
    navSchemes: "పథకాలు",
    navProfile: "ప్రొఫైల్",
    fieldWorkerTitle: "ఫీల్డ్ వర్కర్ డాష్‌బోర్డ్",
    totalAnalyzed: "మొత్తం విశ్లేషించిన జాతులు",
    recentActivity: "ఇటీవలి కార్యాచరణ",
    breedDistribution: 'జాతి పంపిణీ',
    analyticsTitle: "జాతి విశ్లేషణలు",
    searchPlaceholder: "జాతి పేరు ద్వారా శోధించండి...",
    noResults: "మీ శోధనకు సరిపోయే జాతులు కనుగొనబడలేదు.",
    milkQuality: "పాల నాణ్యత",
    fatContent: "కొవ్వు",
    proteinContent: "ప్రోటీన్",
    primaryLocation: "ప్రాథమిక ప్రదేశం",
    qualityRanking: "నాణ్యత ర్యాంకింగ్",
    milkCapacity: "పాల సామర్థ్యం",
    breedDetails: "జాతి వివరాలు",
    suitability: "అనుకూలత",
    monthlyExpense: "నెలవారీ ఖర్చు",
    breedingSeason: "ప్రజనన కాలం",
    matingSuggestions: "జతకట్టే సూచనలు",
    schemesTitle: "ప్రభుత్వ పథకాలు",
    eligibility: "అర్హత",
    learnMore: "మరింత తెలుసుకోండి",
    profileTitle: "ప్రొఫైల్ & సెట్టింగ్‌లు",
    appearanceTitle: "స్వరూపం",
    themeLabel: "అనువర్తనాన్ని ప్రదర్శించడానికి ఒక థీమ్‌ను ఎంచుకోండి.",
    themeLight: "లైట్",
    themeDark: "డార్క్",
    themeSystem: "సిస్టమ్",
    languageTitle: "భాష",
    languageLabel: "మీకు ఇష్టమైన భాషను ఎంచుకోండి.",
    accessibilityTitle: "ప్రాప్యత",
    voiceGuidanceTitle: "వాయిస్ గైడెన్స్",
    voiceGuidanceLabel: "వాయిస్-గైడెడ్ సూచనలు మరియు ఫలితాలను ప్రారంభించండి.",
    otherSettingsTitle: "ఇతర సెట్టింగ్‌లు",
    notificationsLabel: "పుష్ నోటిఫికేషన్‌లను ప్రారంభించండి",
    dataSyncLabel: "ఇప్పుడు డేటాను సమకాలీకరించండి",
    feedbackTitle: 'అభిప్రాయం & మద్దతు',
    feedbackDescription: 'ఏదైనా సలహా ఉందా లేదా బగ్ కనుగొన్నారా? మాకు తెలియజేయండి.',
    feedbackPlaceholder: 'మీ అభిప్రాయాన్ని ఇక్కడ టైప్ చేయండి...',
    submitFeedback: 'అభిప్రాయాన్ని సమర్పించండి',
    submitting: 'సమర్పిస్తోంది',
    feedbackSubmitted: 'సమర్పించబడింది!',
    feedbackSuccessText: 'మీ అభిప్రాయానికి ధన్యవాదాలు!',
    logout: 'లాగ్ అవుట్',
    registrationFormTitle: 'మీ జంతువును నమోదు చేయండి',
    ownerNameLabel: 'యజమాని పేరు',
    ownerContactLabel: 'యజమాని సంప్రదింపు',
    animalTypeLabel: 'జంతువు రకం',
    submitRegistration: 'నమోదును సమర్పించండి',
    cancel: 'రద్దు చేయండి',
    registering: 'నమోదు చేస్తోంది...',
    registrationSuccessTitle: 'నమోదు విజయవంతమైంది!',
    registrationSuccessText: 'మీ జంతువు BPA ప్లాట్‌ఫారమ్‌లో విజయవంతంగా నమోదు చేయబడింది.',
    close: 'మూసివేయండి',
    authTitle: 'పశు పెహచాన్‌కు స్వాగతం',
    authSubtitle: 'కొనసాగించడానికి సైన్ ఇన్ చేయండి లేదా ఖాతాను సృష్టించండి',
    authSendOtp: 'OTP పంపండి',
    authVerifyOtp: 'OTPని ధృవీకరించండి',
    authPhonePlaceholder: 'ఫోన్ నంబర్',
    authNamePlaceholder: 'మీ పేరు',
    authContinue: 'కొనసాగించు',
    authOtpInfo: 'డెమో కోసం, OTPని ఉపయోగించండి:',
    authChangePhone: 'ఫోన్ నంబర్‌ను మార్చండి',
    authInvalidPhone: 'దయచేసి చెల్లుబాటు అయ్యే 10-అంకెల ఫోన్ నంబర్‌ను నమోదు చేయండి.',
    authInvalidName: 'దయచేసి మీ పేరును నమోదు చేయండి.',
    authInvalidOtp: 'చెల్లని OTP. దయచేసి మళ్లీ ప్రయత్నించండి.',
};

const malayalamTexts = {
    title: "പശു പെഹചാൻ",
    subtitle: "AI കന്നുകാലി, എരുമ ഇനം തിരിച്ചറിയൽ",
    uploadTitle: "ഒരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    uploadSubtitle: "ഒരു പശുവിന്റെയോ എരുമയുടെയോ വ്യക്തമായ ഫോട്ടോ അതിന്റെ ഇനം തിരിച്ചറിയാൻ അപ്‌ലോഡ് ചെയ്യുക.",
    uploadButton: "ചിത്രം തിരഞ്ഞെടുക്കുക",
    captureButton: "ക്യാമറയിൽ നിന്ന് പകർത്തുക",
    orText: "അല്ലെങ്കിൽ",
    uploading: "അപ്‌ലോഡ് ചെയ്യുന്നു...",
    analyzing: "നിങ്ങളുടെ ചാമ്പ്യനെ വിശകലനം ചെയ്യുന്നു...",
    identifying: "ഇനം തിരിച്ചറിയുന്നു...",
    errorTitle: "വിശകലനം പരാജയപ്പെട്ടു",
    errorText: "ക്ഷമിക്കണം, ഞങ്ങൾക്ക് ചിത്രം വിശകലനം ചെയ്യാൻ കഴിഞ്ഞില്ല. ഇത് ഒരു പശുവിന്റെയോ എരുമയുടെയോ വ്യക്തമായ ഫോട്ടോ ആയിരിക്കില്ല. ദയവായി മറ്റൊന്ന് ശ്രമിക്കുക.",
    tryAgain: "വീണ്ടും ശ്രമിക്കുക",
    confirmedTitle: "ഇനം തിരിച്ചറിഞ്ഞു!",
    confirmedText: "ഈ മൃഗത്തെ ഇങ്ങനെ തിരിച്ചറിഞ്ഞിരിക്കുന്നു:",
    resultsIntro: (species: string, breedName: string) => `വിശകലനം പൂർത്തിയായി! ഇത് ഒരു ${species.toLowerCase() === 'cow' ? 'പശു' : 'എരുമ'} ആണെന്ന് തോന്നുന്നു. ഇനം ${breedName} ആണ്.`,
    uploadAnother: "മറ്റൊന്ന് അപ്‌ലോഡ് ചെയ്യുക",
    registerBreed: "ഇനം രജിസ്റ്റർ ചെയ്യുക",
    navIdentifier: "ഇനം തിരിച്ചറിയൽ",
    navFieldWorker: "ഫീൽഡ് വർക്കർ",
    navAnalytics: "ബ്രീഡ് അനലിറ്റിക്സ്",
    navSchemes: "പദ്ധതികൾ",
    navProfile: "പ്രൊഫൈൽ",
    fieldWorkerTitle: "ഫീൽഡ് വർക്കർ ഡാഷ്‌ബോർഡ്",
    totalAnalyzed: "വിശകലനം ചെയ്ത മൊത്തം ഇനങ്ങൾ",
    recentActivity: "സമീപകാല പ്രവർത്തനം",
    breedDistribution: 'ഇനങ്ങളുടെ വിതരണം',
    analyticsTitle: "ബ്രീഡ് അനലിറ്റിക്സ്",
    searchPlaceholder: "ഇനത്തിന്റെ പേര് ഉപയോഗിച്ച് തിരയുക...",
    noResults: "നിങ്ങളുടെ തിരയലിനുമായി പൊരുത്തപ്പെടുന്ന ഇനങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    milkQuality: "പാലിന്റെ ഗുണനിലവാരം",
    fatContent: "കൊഴുപ്പ്",
    proteinContent: "പ്രോട്ടീൻ",
    primaryLocation: "പ്രാഥമിക സ്ഥാനം",
    qualityRanking: "ഗുണനിലവാര റാങ്കിംഗ്",
    milkCapacity: "പാൽ ശേഷി",
    breedDetails: "ഇനത്തിന്റെ വിശദാംശങ്ങൾ",
    suitability: "അനുയോജ്യത",
    monthlyExpense: "പ്രതിമാസ ചെലവ്",
    breedingSeason: "പ്രജനന കാലം",
    matingSuggestions: "ഇണചേരൽ നിർദ്ദേശങ്ങൾ",
    schemesTitle: "സർക്കാർ പദ്ധതികൾ",
    eligibility: "യോഗ്യത",
    learnMore: "കൂടുതലറിയുക",
    profileTitle: "പ്രൊഫൈലും ക്രമീകരണങ്ങളും",
    appearanceTitle: "രൂപഭാവം",
    themeLabel: "അപ്ലിക്കേഷൻ പ്രദർശിപ്പിക്കുന്നതിന് ഒരു തീം തിരഞ്ഞെടുക്കുക.",
    themeLight: "ലൈറ്റ്",
    themeDark: "ഡാർക്ക്",
    themeSystem: "സിസ്റ്റം",
    languageTitle: "ഭാഷ",
    languageLabel: "നിങ്ങളുടെ ഇഷ്ട ഭാഷ തിരഞ്ഞെടുക്കുക.",
    accessibilityTitle: "പ്രവേശനക്ഷമത",
    voiceGuidanceTitle: "ശബ്ദ മാർഗ്ഗനിർദ്ദേശം",
    voiceGuidanceLabel: "ശബ്ദ-മാർഗ്ഗനിർദ്ദേശങ്ങളും ഫലങ്ങളും പ്രവർത്തനക്ഷമമാക്കുക.",
    otherSettingsTitle: "മറ്റ് ക്രമീകരണങ്ങൾ",
    notificationsLabel: "പുഷ് അറിയിപ്പുകൾ പ്രവർത്തനക്ഷമമാക്കുക",
    dataSyncLabel: "ഇപ്പോൾ ഡാറ്റ സമന്വയിപ്പിക്കുക",
    feedbackTitle: 'അഭിപ്രായവും പിന്തുണയും',
    feedbackDescription: 'ഒരു നിർദ്ദേശമുണ്ടോ അല്ലെങ്കിൽ ഒരു ബഗ് കണ്ടെത്തിയോ? ഞങ്ങളെ അറിയിക്കുക.',
    feedbackPlaceholder: 'നിങ്ങളുടെ അഭിപ്രായം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
    submitFeedback: 'അഭിപ്രായം സമർപ്പിക്കുക',
    submitting: 'സമർപ്പിക്കുന്നു',
    feedbackSubmitted: 'സമർപ്പിച്ചു!',
    feedbackSuccessText: 'നിങ്ങളുടെ അഭിപ്രായത്തിന് നന്ദി!',
    logout: 'ലോഗൗട്ട് ചെയ്യുക',
    registrationFormTitle: 'നിങ്ങളുടെ മൃഗത്തെ രജിസ്റ്റർ ചെയ്യുക',
    ownerNameLabel: 'ഉടമയുടെ പേര്',
    ownerContactLabel: 'ഉടമയുടെ കോൺടാക്റ്റ്',
    animalTypeLabel: 'മൃഗത്തിന്റെ തരം',
    submitRegistration: 'രജിസ്ട്രേഷൻ സമർപ്പിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    registering: 'രജിസ്റ്റർ ചെയ്യുന്നു...',
    registrationSuccessTitle: 'രജിസ്ട്രേഷൻ വിജയിച്ചു!',
    registrationSuccessText: 'നിങ്ങളുടെ മൃഗത്തെ ബിപിഎ പ്ലാറ്റ്‌ഫോമിൽ വിജയകരമായി രജിസ്റ്റർ ചെയ്തു.',
    close: 'അടയ്ക്കുക',
    authTitle: 'പശു പെഹചാനിലേക്ക് സ്വാഗതം',
    authSubtitle: 'തുടരുന്നതിന് സൈൻ ഇൻ ചെയ്യുക അല്ലെങ്കിൽ ഒരു അക്കൗണ്ട് ഉണ്ടാക്കുക',
    authSendOtp: 'ഒടിപി അയയ്ക്കുക',
    authVerifyOtp: 'ഒടിപി പരിശോധിക്കുക',
    authPhonePlaceholder: 'ഫോൺ നമ്പർ',
    authNamePlaceholder: 'നിങ്ങളുടെ പേര്',
    authContinue: 'തുടരുക',
    authOtpInfo: 'ഡെമോയ്ക്കായി, ഒടിപി ഉപയോഗിക്കുക:',
    authChangePhone: 'ഫോൺ നമ്പർ മാറ്റുക',
    authInvalidPhone: 'ദയവായി സാധുവായ 10 അക്ക ഫോൺ നമ്പർ നൽകുക.',
    authInvalidName: 'ദയവായി നിങ്ങളുടെ പേര് നൽകുക.',
    authInvalidOtp: 'അസാധുവായ ഒടിപി. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
};

const tamilTexts = {
    title: "பசு பெஹचान",
    subtitle: "AI கால்நடை மற்றும் எருமை இனம் அடையாளங்காட்டி",
    uploadTitle: "ഒരു படத்தை பதிவேற்றவும்",
    uploadSubtitle: "ഒരു மாடு அல்லது எருமையின் தெளிவான புகைப்படத்தை அதன் இனத்தை அடையாளம் காண பதிவேற்றவும்.",
    uploadButton: "படத்தைத் தேர்ந்தெடுக்கவும்",
    captureButton: "கேமராவிலிருந்து பிடிக்கவும்",
    orText: "அல்லது",
    uploading: "பதிவேற்றுகிறது...",
    analyzing: "உங்கள் πρωταθλητήயை பகுப்பாய்வு செய்கிறது...",
    identifying: "இனத்தை அடையாளம் காண்கிறது...",
    errorTitle: "பகுப்பாய்வு தோல்வியடைந்தது",
    errorText: "மன்னிக்கவும், எங்களால் படத்தை பகுப்பாய்வு செய்ய முடியவில்லை. இது ஒரு மாடு அல்லது எருமையின் தெளிவான புகைப்படமாக இல்லாமல் இருக்கலாம். தயவுசெய்து இன்னொன்றை முயற்சிக்கவும்.",
    tryAgain: "மீண்டும் முயற்சிக்கவும்",
    confirmedTitle: "இனம் அடையாளம் காணப்பட்டது!",
    confirmedText: "இந்த விலங்கு என அடையாளம் காணப்பட்டுள்ளது:",
    resultsIntro: (species: string, breedName: string) => `பகுப்பாய்வு முடிந்தது! இது ஒரு ${species.toLowerCase() === 'cow' ? 'மாடு' : 'எருமை'} போல் தெரிகிறது. இனம் ${breedName}.`,
    uploadAnother: "மற்றொன்றைப் பதிவேற்றவும்",
    registerBreed: "இனத்தை பதிவு செய்யவும்",
    navIdentifier: "இனம் அடையாளங்காட்டி",
    navFieldWorker: "களப்பணியாளர்",
    navAnalytics: "இனப் பகுப்பாய்வு",
    navSchemes: "திட்டங்கள்",
    navProfile: "சுயவிவரம்",
    fieldWorkerTitle: "களப்பணியாளர் டாஷ்போர்டு",
    totalAnalyzed: "மொத்தமாக பகுப்பாய்வு செய்யப்பட்ட இனங்கள்",
    recentActivity: "சமீபத்திய செயல்பாடு",
    breedDistribution: 'இனப் பரவல்',
    analyticsTitle: "இனப் பகுப்பாய்வு",
    searchPlaceholder: "இனத்தின் பெயரால் தேடவும்...",
    noResults: "உங்கள் தேடலுடன் பொருந்தும் இனங்கள் எதுவும் இல்லை.",
    milkQuality: "பாலின் தரம்",
    fatContent: "கொழுப்பு",
    proteinContent: "புரதம்",
    primaryLocation: "முதன்மை இடம்",
    qualityRanking: "தரவரிசை",
    milkCapacity: "பால் கொள்ளளவு",
    breedDetails: "இன விவரங்கள்",
    suitability: "பொருத்தம்",
    monthlyExpense: "மாதாந்திர செலவு",
    breedingSeason: "இனப்பெருக்க காலம்",
    matingSuggestions: "இனச்சேர்க்கை பரிந்துரைகள்",
    schemesTitle: "அரசு திட்டங்கள்",
    eligibility: "தகுதி",
    learnMore: "மேலும் அறிக",
    profileTitle: "சுயவிவரம் & அமைப்புகள்",
    appearanceTitle: "தோற்றம்",
    themeLabel: "பயன்பாட்டைக் காண்பிக்க ஒரு தீம் தேர்ந்தெடுக்கவும்.",
    themeLight: "ஒளி",
    themeDark: "இருள்",
    themeSystem: "கணினி",
    languageTitle: "மொழி",
    languageLabel: "உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.",
    accessibilityTitle: "அணுகல்தன்மை",
    voiceGuidanceTitle: "குரல் வழிகாட்டுதல்",
    voiceGuidanceLabel: "குரல் வழிகாட்டுதல் வழிமுறைகள் மற்றும் முடிவுகளை இயக்கவும்.",
    otherSettingsTitle: "பிற அமைப்புகள்",
    notificationsLabel: "புஷ் அறிவிப்புகளை இயக்கவும்",
    dataSyncLabel: "இப்போது தரவை ஒத்திசைக்கவும்",
    feedbackTitle: 'கருத்து மற்றும் ஆதரவு',
    feedbackDescription: 'ഒരു பரிந்துரை உள்ளதா அல்லது ஒரு பிழை காணப்பட்டதா? எங்களுக்குத் தெரியப்படுத்துங்கள்.',
    feedbackPlaceholder: 'உங்கள் கருத்தை இங்கே தட்டச்சு செய்யவும்...',
    submitFeedback: 'கருத்தை சமர்ப்பிக்கவும்',
    submitting: 'சமர்ப்பிக்கிறது',
    feedbackSubmitted: 'சமர்ப்பிக்கப்பட்டது!',
    feedbackSuccessText: 'உங்கள் கருத்திற்கு நன்றி!',
    logout: 'வெளியேறு',
    registrationFormTitle: 'உங்கள் விலங்கை பதிவு செய்யுங்கள்',
    ownerNameLabel: 'உரிமையாளர் பெயர்',
    ownerContactLabel: 'உரிமையாளர் தொடர்பு',
    animalTypeLabel: 'விலங்கு வகை',
    submitRegistration: 'பதிவைச் சமர்ப்பிக்கவும்',
    cancel: 'ரத்துசெய்',
    registering: 'பதிவு செய்கிறது...',
    registrationSuccessTitle: 'பதிவு வெற்றி!',
    registrationSuccessText: 'உங்கள் விலங்கு BPA தளத்தில் வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளது.',
    close: 'மூடு',
    authTitle: 'பசு பெஹचानக்கு வரவேற்கிறோம்',
    authSubtitle: 'தொடர உள்நுழையவும் அல்லது கணக்கை உருவாக்கவும்',
    authSendOtp: 'OTP அனுப்பு',
    authVerifyOtp: 'OTP சரிபார்க்கவும்',
    authPhonePlaceholder: 'தொலைபேசி எண்',
    authNamePlaceholder: 'உங்கள் பெயர்',
    authContinue: 'தொடரவும்',
    authOtpInfo: 'டெமோவிற்கு, OTP ஐப் பயன்படுத்தவும்:',
    authChangePhone: 'தொலைபேசி எண்ணை மாற்றவும்',
    authInvalidPhone: 'தயவுசெய்து சரியான 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்.',
    authInvalidName: 'தயவுசெய்து உங்கள் பெயரை உள்ளிடவும்.',
    authInvalidOtp: 'தவறான OTP. దయచేసి మళ్లీ ప్రయత్నించండి.',
};

const kannadaTexts = {
    title: "ಪಶು ಪೆಹಚಾನ್",
    subtitle: "AI ಜಾನುವಾರು ಮತ್ತು ಎಮ್ಮೆ ತಳಿ ಗುರುತಿಸುವಿಕೆ",
    uploadTitle: "ಒಂದು ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    uploadSubtitle: "ಅದರ ತಳಿಯನ್ನು ಗುರುತಿಸಲು ಒಂದು ಹಸು ಅಥವಾ ಎಮ್ಮೆಯ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    uploadButton: "ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    captureButton: "ಕ್ಯಾಮೆರಾದಿಂದ ಸೆರೆಹಿಡಿಯಿರಿ",
    orText: "ಅಥವಾ",
    uploading: "ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    analyzing: "ನಿಮ್ಮ ಚಾಂಪಿಯನ್ ಅನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    identifying: "ತಳಿಯನ್ನು ಗುರುತಿಸಲಾಗುತ್ತಿದೆ...",
    errorTitle: "ವಿಶ್ಲೇಷಣೆ ವಿಫಲವಾಗಿದೆ",
    errorText: "ಕ್ಷಮಿಸಿ, ನಾವು ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಇದು ಹಸು ಅಥವಾ ಎಮ್ಮೆಯ ಸ್ಪಷ್ಟ ಫೋಟೋ ಆಗಿರದಿರಬಹುದು. ದಯವಿಟ್ಟು ಇನ್ನೊಂದನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
    tryAgain: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    confirmedTitle: "ತಳಿ ಗುರುತಿಸಲಾಗಿದೆ!",
    confirmedText: "ಈ ಪ್ರಾಣಿಯನ್ನು ಹೀಗೆ ಗುರುತಿಸಲಾಗಿದೆ:",
    resultsIntro: (species: string, breedName: string) => `ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ! ಇದು ${species.toLowerCase() === 'cow' ? 'ಹಸು' : 'ಎಮ್ಮೆ'} ಎಂದು ತೋರುತ್ತದೆ. ತಳಿ ${breedName}.`,
    uploadAnother: "ಮತ್ತೊಂದನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    registerBreed: "ತಳಿಯನ್ನು ನೋಂದಾಯಿಸಿ",
    navIdentifier: "ತಳಿ ಗುರುತಿಸುವಿಕೆ",
    navFieldWorker: "ಕ್ಷೇತ್ರ ಕಾರ್ಯಕರ್ತ",
    navAnalytics: "ತಳಿ ವಿಶ್ಲೇಷಣೆ",
    navSchemes: "ಯೋಜನೆಗಳು",
    navProfile: "ಪ್ರೊಫೈಲ್",
    fieldWorkerTitle: "ಕ್ಷೇತ್ರ ಕಾರ್ಯಕರ್ತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    totalAnalyzed: "ವಿಶ್ಲೇಷಿಸಿದ ಒಟ್ಟು ತಳಿಗಳು",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    breedDistribution: 'ತಳಿ ವಿತರಣೆ',
    analyticsTitle: "ತಳಿ ವಿಶ್ಲೇಷಣೆ",
    searchPlaceholder: "ತಳಿಯ ಹೆಸರಿನಿಂದ ಹುಡುಕಿ...",
    noResults: "ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಯಾವುದೇ ತಳಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    milkQuality: "ಹಾಲಿನ ಗುಣಮಟ್ಟ",
    fatContent: "ಕೊಬ್ಬು",
    proteinContent: "ಪ್ರೋಟೀన్",
    primaryLocation: "ಪ್ರಾಥಮಿಕ ಸ್ಥಳ",
    qualityRanking: "ಗುಣಮಟ್ಟದ ಶ್ರೇಯಾಂಕ",
    milkCapacity: "ಹಾಲು ಸಾಮರ್ಥ್ಯ",
    breedDetails: "ತಳಿ ವಿವರಗಳು",
    suitability: "ಸೂಕ್ತತೆ",
    monthlyExpense: "ಮಾಸಿಕ ವೆಚ್ಚ",
    breedingSeason: "ಸಂತಾನೋತ್ಪತ್ತಿ ಕಾಲ",
    matingSuggestions: "ಸಂಗಾತಿ ಸಲಹೆಗಳು",
    schemesTitle: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    eligibility: "ಅರ್ಹತೆ",
    learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
    profileTitle: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    appearanceTitle: "ಗೋಚರತೆ",
    themeLabel: "ಅಪ್ಲಿಕೇಶನ್ ಪ್ರದರ್ಶಿಸಲು ಒಂದು ಥೀಮ್ ಆಯ್ಕೆಮಾಡಿ.",
    themeLight: "ಬೆಳಕು",
    themeDark: "ಕತ್ತಲೆ",
    themeSystem: "ಸಿಸ್ಟಮ್",
    languageTitle: "ಭಾಷೆ",
    languageLabel: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    accessibilityTitle: "ಪ್ರವೇಶಿಸುವಿಕೆ",
    voiceGuidanceTitle: "ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ",
    voiceGuidanceLabel: "ಧ್ವನಿ-ಮಾರ್ಗದರ್ಶಿ ಸೂಚನೆಗಳು ಮತ್ತು ಫಲಿತಾಂಶಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.",
    otherSettingsTitle: "ಇತರ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    notificationsLabel: "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
    dataSyncLabel: "ಈಗ ಡೇಟಾವನ್ನು ಸಿಂಕ್ ಮಾಡಿ",
    feedbackTitle: 'ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಬೆಂಬಲ',
    feedbackDescription: 'ಒಂದು ಸಲಹೆ ಇದೆಯೇ ಅಥವಾ ದೋಷ ಕಂಡುಬಂದಿದೆಯೇ? ನಮಗೆ ತಿಳಿಸಿ.',
    feedbackPlaceholder: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    submitFeedback: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
    submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ',
    feedbackSubmitted: 'ಸಲ್ಲಿಸಲಾಗಿದೆ!',
    feedbackSuccessText: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!',
    logout: 'ಲಾಗ್ ಔಟ್ ಮಾಡಿ',
    registrationFormTitle: 'ನಿಮ್ಮ ಪ್ರಾಣಿಯನ್ನು ನೋಂದಾಯಿಸಿ',
    ownerNameLabel: 'ಮಾಲೀಕರ ಹೆಸರು',
    ownerContactLabel: 'ಮಾಲೀಕರ ಸಂಪರ್ಕ',
    animalTypeLabel: 'ಪ್ರಾಣಿ ಪ್ರಕಾರ',
    submitRegistration: 'ನೋಂದಣಿ ಸಲ್ಲಿಸಿ',
    cancel: 'ರದ್ದುಗೊಳಿಸಿ',
    registering: 'ನೋಂದಾಯಿಸಲಾಗುತ್ತಿದೆ...',
    registrationSuccessTitle: 'ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!',
    registrationSuccessText: 'ನಿಮ್ಮ ಪ್ರಾಣಿಯನ್ನು ಬಿಪಿಎ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ.',
    close: 'ಮುಚ್ಚಿ',
    authTitle: 'ಪಶು ಪೆಹಚಾನ್‌ಗೆ ಸ್ವಾಗತ',
    authSubtitle: 'ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ ಅಥವಾ ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    authSendOtp: 'ಒಟಿಪಿ ಕಳುಹಿಸಿ',
    authVerifyOtp: 'ಒಟಿಪಿ ಪರಿಶೀಲಿಸಿ',
    authPhonePlaceholder: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
    authNamePlaceholder: 'ನಿಮ್ಮ ಹೆಸರು',
    authContinue: 'ಮುಂದುವರಿಸಿ',
    authOtpInfo: 'ಡೆಮೊಗಾಗಿ, ಒಟಿಪಿ ಬಳಸಿ:',
    authChangePhone: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆಯನ್ನು ಬದಲಾಯಿಸಿ',
    authInvalidPhone: 'ದಯವಿಟ್ಟು ಮಾನ್ಯ 10-ಅಂಕಿಯ ದೂರವಾಣಿ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
    authInvalidName: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.',
    authInvalidOtp: 'ಅಮಾನ್ಯ ಒಟಿಪಿ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
};

export const TEXTS = {
  [Language.EN]: englishTexts,
  [Language.HI]: hindiTexts,
  [Language.MR]: marathiTexts,
  [Language.GU]: gujaratiTexts,
  [Language.TE]: teluguTexts,
  [Language.ML]: malayalamTexts,
  [Language.TA]: tamilTexts,
  [Language.KN]: kannadaTexts,
};

export const MOCK_FIELD_WORKER_DATA: FieldWorkData[] = [
    { id: 1, breed: 'Gir', location: 'Anand, Gujarat', date: '2024-07-20' },
    { id: 2, breed: 'Sahiwal', location: 'Ludhiana, Punjab', date: '2024-07-19' },
    { id: 3, breed: 'Murrah', location: 'Rohtak, Haryana', date: '2024-07-19' },
    { id: 4, breed: 'Red Sindhi', location: 'Karachi, Sindh (Origin)', date: '2024-07-18' },
    { id: 5, breed: 'Gir', location: 'Junagadh, Gujarat', date: '2024-07-17' },
];

export const MOCK_BREED_ANALYTICS_DATA: BreedAnalyticsData[] = [
    { 
        id: 1, name: 'Gir', milkQuality: { fat: '4.5-5.0%', protein: '3.2-3.5%' }, location: 'Gujarat', ranking: 5,
        suitability: { 
            [Language.EN]: 'Excellent for high-quality A2 milk production.', 
            [Language.HI]: 'उच्च गुणवत्ता वाले A2 दूध उत्पादन के लिए उत्कृष्ट।',
            [Language.MR]: 'उच्च-गुणवत्तेच्या A2 दूध उत्पादनासाठी उत्कृष्ट.',
            [Language.GU]: 'ઉચ્ચ-ગુણવત્તાવાળા A2 દૂધના ઉત્પાદન માટે ઉત્તમ.',
            [Language.TE]: 'అధిక-నాణ్యత గల A2 పాల ఉత్పత్తికి అద్భుతమైనది.',
            [Language.ML]: 'ഉയർന്ന നിലവാരമുള്ള എ2 പാൽ ഉൽപാദനത്തിന് മികച്ചതാണ്.',
            [Language.TA]: 'உயர்தர A2 பால் உற்பத்திக்கு சிறந்தது.',
            [Language.KN]: 'ಉತ್ತಮ-ಗುಣಮಟ್ಟದ A2 ಹಾಲು ಉತ್ಪಾದನೆಗೆ ಅತ್ಯುತ್ತಮವಾಗಿದೆ.',
        },
        monthlyExpense: { 
            [Language.EN]: '₹3,500 - ₹5,000 per animal.', 
            [Language.HI]: '₹3,500 - ₹5,000 प्रति पशु।',
            [Language.MR]: '₹3,500 - ₹5,000 प्रति प्राणी.',
            [Language.GU]: '₹3,500 - ₹5,000 પ્રતિ પ્રાણી.',
            [Language.TE]: 'జంతువుకు ₹3,500 - ₹5,000.',
            [Language.ML]: 'ഒരു മൃഗത്തിന് ₹3,500 - ₹5,000.',
            [Language.TA]: 'ഒരു விலங்குக்கு ₹3,500 - ₹5,000.',
            [Language.KN]: 'ಪ್ರತಿ ಪ್ರಾಣಿಗೆ ₹3,500 - ₹5,000.',
        },
        breedingSeason: { 
            [Language.EN]: 'Year-round, with peak fertility in summer.', 
            [Language.HI]: 'साल भर, गर्मियों में चरम प्रजनन क्षमता के साथ।',
            [Language.MR]: 'वर्षभर, उन्हाळ्यात सर्वाधिक प्रजनन क्षमता.',
            [Language.GU]: 'આખું વર્ષ, ઉનાળામાં મહત્તમ પ્રજનનક્ષમતા સાથે.',
            [Language.TE]: 'ఏడాది పొడవునా, వేసవిలో గరిష్ట సంతానోత్పత్తితో.',
            [Language.ML]: 'വർഷം മുഴുവനും, വേനൽക്കാലത്ത് ഉയർന്ന പ്രത്യുൽപാദനക്ഷമത.',
            [Language.TA]: 'ஆண்டு முழுவதும், கோடையில் உச்சகட்ட கருவுறுதலுடன்.',
            [Language.KN]: 'ವರ್ಷಪೂರ್ತಿ, ಬೇಸಿಗೆಯಲ್ಲಿ ಗರಿಷ್ಠ ಫಲವತ್ತತೆ.',
        },
        matingSuggestions: { 
            [Language.EN]: ['Sahiwal', 'Red Sindhi'], 
            [Language.HI]: ['साहीवाल', 'लाल सिंधी'],
            [Language.MR]: ['साहिवाल', 'लाल सिंधी'],
            [Language.GU]: ['સાહિવાલ', 'લાલ સિંધી'],
            [Language.TE]: ['సాహివాల్', 'రెడ్ సింధీ'],
            [Language.ML]: ['സഹിവാൾ', 'റെഡ് സിന്ധി'],
            [Language.TA]: ['சாஹிவால்', 'சிவப்பு சிந்தி'],
            [Language.KN]: ['ಸಾಹಿವಾಲ್', 'ಕೆಂಪು ಸಿಂಧಿ'],
        }
    },
    { 
        id: 2, name: 'Sahiwal', milkQuality: { fat: '4.0-4.5%', protein: '3.0-3.4%' }, location: 'Punjab, Haryana', ranking: 5,
        suitability: { 
            [Language.EN]: 'High milk yield and heat tolerant.', 
            [Language.HI]: 'उच्च दूध उपज और गर्मी सहनशील।',
            [Language.MR]: 'उच्च दूध उत्पादन आणि उष्णता सहनशील.',
            [Language.GU]: 'ઉચ્ચ દૂધ ઉપજ અને ગરમી સહનશીલ.',
            [Language.TE]: 'అధిక పాల దిగుబడి మరియు వేడిని తట్టుకోగలదు.',
            [Language.ML]: 'ഉയർന്ന പാൽ ഉൽപാദനവും ചൂട് സഹിക്കാനുള്ള കഴിവും.',
            [Language.TA]: 'அதிக பால் மகசூல் மற்றும் வெப்பம் தாங்கும் தன்மை.',
            [Language.KN]: 'ಹೆಚ್ಚಿನ ಹಾಲು ಇಳುವರಿ ಮತ್ತು ಶಾಖ ಸಹಿಷ್ಣು.',
        },
        monthlyExpense: { 
            [Language.EN]: '₹3,000 - ₹4,500 per animal.', 
            [Language.HI]: '₹3,000 - ₹4,500 प्रति पशु।',
            [Language.MR]: '₹3,000 - ₹4,500 प्रति प्राणी.',
            [Language.GU]: '₹3,000 - ₹4,500 પ્રતિ પ્રાણી.',
            [Language.TE]: 'జంతువుకు ₹3,000 - ₹4,500.',
            [Language.ML]: 'ഒരു മൃഗത്തിന് ₹3,000 - ₹4,500.',
            [Language.TA]: 'ஒரு விலங்குக்கு ₹3,000 - ₹4,500.',
            [Language.KN]: 'ಪ್ರತಿ ಪ್ರಾಣಿಗೆ ₹3,000 - ₹4,500.',
        },
        breedingSeason: { 
            [Language.EN]: 'Year-round, adaptable to various climates.', 
            [Language.HI]: 'साल भर, विभिन्न जलवायु के लिए अनुकूलनीय।',
            [Language.MR]: 'वर्षभर, विविध हवामानांशी जुळवून घेणारे.',
            [Language.GU]: 'આખું વર્ષ, વિવિધ આબોહવાને અનુકૂળ.',
            [Language.TE]: 'ఏడాది పొడవునా, వివిధ వాతావరణాలకు అనుకూలమైనది.',
            [Language.ML]: 'വർഷം മുഴുവനും, വിവിധ കാലാവസ്ഥകളുമായി പൊരുത്തപ്പെടാൻ കഴിയും.',
            [Language.TA]: 'ஆண்டு முழுவதும், பல்வேறு காலநிலைகளுக்கு ஏற்புடையது.',
            [Language.KN]: 'ವರ್ಷಪೂರ್ತಿ, ವಿವಿಧ ಹವಾಮಾನಗಳಿಗೆ ಹೊಂದಿಕೊಳ್ಳಬಲ್ಲದು.',
        },
        matingSuggestions: { 
            [Language.EN]: ['Gir', 'Tharparkar'], 
            [Language.HI]: ['गिर', 'थारपारकर'],
            [Language.MR]: ['गीर', 'थरपारकर'],
            [Language.GU]: ['ગીર', 'થરપારકર'],
            [Language.TE]: ['గిర్', 'థార్పార్కర్'],
            [Language.ML]: ['ഗിർ', 'താർപാർക്കർ'],
            [Language.TA]: ['கிர்', 'தார்பார்க்கர்'],
            [Language.KN]: ['ಗಿರ್', 'ಥಾರ್ಪಾರ್ಕರ್'],
        }
    },
    { 
        id: 3, name: 'Murrah Buffalo', milkQuality: { fat: '7.0-8.0%', protein: '4.0-4.5%' }, location: 'Haryana, Punjab', ranking: 5,
        suitability: { 
            [Language.EN]: 'Premium for high-fat milk, ideal for dairy products.', 
            [Language.HI]: 'उच्च वसा वाले दूध के लिए प्रीमियम, डेयरी उत्पादों के लिए आदर्श।',
            [Language.MR]: 'उच्च चरबीयुक्त दुधासाठी प्रीमियम, दुग्धजन्य पदार्थांसाठी आदर्श.',
            [Language.GU]: 'ઉચ્ચ ચરબીવાળા દૂધ માટે પ્રીમિયમ, ડેરી ઉત્પાદનો માટે આદર્શ.',
            [Language.TE]: 'అధిక-కొవ్వు పాల కోసం ప్రీమియం, పాల ఉత్పత్తులకు అనువైనది.',
            [Language.ML]: 'ഉയർന്ന കൊഴുപ്പുള്ള പാലിന് പ്രീമിയം, പാൽ ഉൽപ്പന്നങ്ങൾക്ക് അനുയോജ്യം.',
            [Language.TA]: 'அதிக கொழுப்புள்ள பாலுக்கான பிரீமியம், பால் பொருட்களுக்கு ஏற்றது.',
            [Language.KN]: 'ಹೆಚ್ಚಿನ ಕೊಬ್ಬಿನ ಹಾಲಿಗೆ ಪ್ರೀಮિયಂ, ಡೈರಿ ಉತ್ಪನ್ನಗಳಿಗೆ ಸೂಕ್ತವಾಗಿದೆ.',
        },
        monthlyExpense: { 
            [Language.EN]: '₹4,000 - ₹6,000 per animal.', 
            [Language.HI]: '₹4,000 - ₹6,000 प्रति पशु।',
            [Language.MR]: '₹4,000 - ₹6,000 प्रति प्राणी.',
            [Language.GU]: '₹4,000 - ₹6,000 પ્રતિ પ્રાણી.',
            [Language.TE]: 'జంతువుకు ₹4,000 - ₹6,000.',
            [Language.ML]: 'ഒരു മൃഗത്തിന് ₹4,000 - ₹6,000.',
            [Language.TA]: 'ஒரு விலங்குக்கு ₹4,000 - ₹6,000.',
            [Language.KN]: 'ಪ್ರತಿ ಪ್ರಾಣಿಗೆ ₹4,000 - ₹6,000.',
        },
        breedingSeason: { 
            [Language.EN]: 'September to February is optimal.', 
            [Language.HI]: 'सितंबर से फरवरी का समय इष्टतम है।',
            [Language.MR]: 'सप्टेंबर ते फेब्रुवारी हा काळ उत्तम असतो.',
            [Language.GU]: 'સપ્ટેમ્બરથી ફેબ્રુઆરી શ્રેષ્ઠ છે.',
            [Language.TE]: 'సెప్టెంబర్ నుండి ఫిబ్రవరి వరకు ఉత్తమమైనది.',
            [Language.ML]: 'സെപ്റ്റംബർ മുതൽ ഫെബ്രുവരി വരെയാണ് ഏറ്റവും അനുയോജ്യം.',
            [Language.TA]: 'செப்டம்பர் முதல் பிப்ரவரி வரை உகந்தது.',
            [Language.KN]: 'ಸೆಪ್ಟೆಂಬರ್ ನಿಂದ ಫೆಬ್ರವರಿ ಅತ್ಯುತ್ತಮವಾಗಿದೆ.',
        },
        matingSuggestions: { 
            [Language.EN]: ['Nili-Ravi', 'Mehsana'], 
            [Language.HI]: ['नीली-रावी', 'मेहसाणा'],
            [Language.MR]: ['नीली-रवी', 'मेहसाणा'],
            [Language.GU]: ['નીલી-રવી', 'મહેસાણા'],
            [Language.TE]: ['నీలి-రవి', 'మెహసానా'],
            [Language.ML]: ['നീലി-രവി', 'മെഹ്‌സാന'],
            [Language.TA]: ['நீலி-ரவி', 'மெஹ்சானா'],
            [Language.KN]: ['ನೀಲಿ-ರವಿ', 'ಮೆಹಸಾನಾ'],
        }
    },
    // Adding more translations for other breeds would follow the same pattern...
    { 
        id: 4, name: 'Red Sindhi', milkQuality: { fat: '4.0-4.2%', protein: '3.1-3.3%' }, location: 'Odisha, Tamil Nadu', ranking: 4,
        suitability: { [Language.EN]: 'Highly adaptable and good milk producer.', [Language.HI]: 'अत्यधिक अनुकूलनीय और अच्छी दूध उत्पादक।' },
        monthlyExpense: { [Language.EN]: '₹3,200 - ₹4,800 per animal.', [Language.HI]: '₹3,200 - ₹4,800 प्रति पशु।' },
        breedingSeason: { [Language.EN]: 'Breeds regularly throughout the year.', [Language.HI]: 'साल भर नियमित रूप से प्रजनन करती है।' },
        matingSuggestions: { [Language.EN]: ['Gir', 'Sahiwal'], [Language.HI]: ['गिर', 'साहीवाल'] }
    },
    { 
        id: 5, name: 'Tharparkar', milkQuality: { fat: '4.2-4.8%', protein: '3.2-3.6%' }, location: 'Rajasthan', ranking: 4,
        suitability: { [Language.EN]: 'Excellent dual-purpose breed, very hardy and drought-resistant.', [Language.HI]: 'उत्कृष्ट दोहरे उद्देश्य वाली नस्ल, बहुत कठोर और सूखा प्रतिरोधी।' },
        monthlyExpense: { [Language.EN]: '₹2,500 - ₹4,000 per animal (low maintenance).', [Language.HI]: '₹2,500 - ₹4,000 प्रति पशु (कम रखरखाव)।' },
        breedingSeason: { [Language.EN]: 'Year-round, known for good fertility.', [Language.HI]: 'साल भर, अच्छी प्रजनन क्षमता के लिए जानी जाती है।' },
        matingSuggestions: { [Language.EN]: ['Sahiwal', 'Kankrej'], [Language.HI]: ['साहीवाल', 'कांकरेज'] }
    },
    { 
        id: 6, name: 'Deoni', milkQuality: { fat: '3.5-4.0%', protein: '3.0-3.2%' }, location: 'Maharashtra, Karnataka', ranking: 3,
        suitability: { [Language.EN]: 'Good dual-purpose (draft and milk).', [Language.HI]: 'अच्छे दोहरे उद्देश्य (प्रारूप और दूध)।' },
        monthlyExpense: { [Language.EN]: '₹2,800 - ₹4,200 per animal.', [Language.HI]: '₹2,800 - ₹4,200 प्रति पशु।' },
        breedingSeason: { [Language.EN]: 'Consistent breeding cycles year-round.', [Language.HI]: 'साल भर लगातार प्रजनन चक्र।' },
        matingSuggestions: { [Language.EN]: ['Gir', 'Local hardy breeds'], [Language.HI]: ['गिर', 'स्थानीय हार्डी नस्लें'] }
    },
    {
        id: 7, name: 'Kankrej', milkQuality: { fat: '4.5-5.0%', protein: '3.3-3.7%' }, location: 'Gujarat, Rajasthan', ranking: 4,
        suitability: { [Language.EN]: 'Excellent dual-purpose (draft & milk), known for its "Sवाई Chal" gait.', [Language.HI]: 'उत्कृष्ट दोहरे उद्देश्य (प्रारूप और दूध), अपनी "सवाई चाल" के लिए जाना जाता है।' },
        monthlyExpense: { [Language.EN]: '₹2,800 - ₹4,200 per animal.', [Language.HI]: '₹2,800 - ₹4,200 प्रति पशु।' },
        breedingSeason: { [Language.EN]: 'Year-round, very hardy and adaptable.', [Language.HI]: 'साल भर, बहुत कठोर और अनुकूलनीय।' },
        matingSuggestions: { [Language.EN]: ['Tharparkar', 'Gir'], [Language.HI]: ['थारपारकर', 'गिर'] }
    },
    {
        id: 8, name: 'Ongole', milkQuality: { fat: '3.5-4.5%', protein: '3.0-3.4%' }, location: 'Andhra Pradesh', ranking: 3,
        suitability: { [Language.EN]: 'Primarily a draft breed, known for strength and stamina. Moderate milk yield.', [Language.HI]: 'मुख्य रूप से एक प्रारूप नस्ल, जो अपनी ताकत और सहनशक्ति के लिए जानी जाती है। मध्यम दूध उपज।' },
        monthlyExpense: { [Language.EN]: '₹2,500 - ₹4,000 per animal.', [Language.HI]: '₹2,500 - ₹4,000 प्रति पशु।' },
        breedingSeason: { [Language.EN]: 'Adapts well to hot and dry climates, breeds year-round.', [Language.HI]: 'गर्म और शुष्क जलवायु के लिए अच्छी तरह से अनुकूल है, साल भर प्रजनन करती है।' },
        matingSuggestions: { [Language.EN]: ['Local robust breeds', 'Hallikar'], [Language.HI]: ['स्थानीय मजबूत नस्लें', 'हल्लिकर'] }
    },
    {
        id: 9, name: 'Mehsana Buffalo', milkQuality: { fat: '6.5-7.5%', protein: '3.8-4.2%' }, location: 'Gujarat', ranking: 4,
        suitability: { [Language.EN]: 'Good milk producer, crossbreed of Murrah and Surti.', [Language.HI]: 'अच्छी दूध उत्पादक, मुर्रा और सुरती की संकर नस्ल।' },
        monthlyExpense: { [Language.EN]: '₹3,800 - ₹5,500 per animal.', [Language.HI]: '₹3,800 - ₹5,500 प्रति पशु।' },
        breedingSeason: { [Language.EN]: 'Mainly from October to March.', [Language.HI]: 'मुख्य रूप से अक्टूबर से मार्च तक।' },
        matingSuggestions: { [Language.EN]: ['Murrah', 'Surti'], [Language.HI]: ['मुर्रा', 'सुरती'] }
    },
    {
        id: 10, name: 'Jaffarabadi Buffalo', milkQuality: { fat: '7.5-8.5%', protein: '4.2-4.6%' }, location: 'Gujarat (Gir Forest)', ranking: 5,
        suitability: { [Language.EN]: 'Heaviest buffalo breed, excellent high-fat milk for ghee production.', [Language.HI]: 'सबसे भारी भैंस नस्ल, घी उत्पादन के लिए उत्कृष्ट उच्च वसा वाला दूध।' },
        monthlyExpense: { [Language.EN]: '₹4,500 - ₹6,500 per animal (high feed intake).', [Language.HI]: '₹4,500 - ₹6,500 प्रति पशु (उच्च चारा सेवन)।' },
        breedingSeason: { [Language.EN]: 'Seasonal, primarily post-monsoon.', [Language.HI]: 'मौसमी, मुख्य रूप से मानसून के बाद।' },
        matingSuggestions: { [Language.EN]: ['Murrah (for milk yield)', 'Local hardy breeds'], [Language.HI]: ['मुर्रा (दूध की उपज के लिए)', 'स्थानीय हार्डी नस्लें'] }
    },
    {
        id: 11, name: 'Hallikar', milkQuality: { fat: '3.0-3.5%', protein: '2.8-3.1%' }, location: 'Karnataka', ranking: 3,
        suitability: { [Language.EN]: 'Classic draft breed, known for its speed and endurance. Low milk yield.', [Language.HI]: 'क्लासिक प्रारूप नस्ल, अपनी गति और सहनशक्ति के लिए जानी जाती है। कम दूध उपज।' },
        monthlyExpense: { [Language.EN]: '₹2,200 - ₹3,500 per animal (very low maintenance).', [Language.HI]: '₹2,200 - ₹3,500 प्रति पशु (बहुत कम रखरखाव)।' },
        breedingSeason: { [Language.EN]: 'Hardy and breeds throughout the year.', [Language.HI]: 'कठोर और साल भर प्रजनन करती है।' },
        matingSuggestions: { [Language.EN]: ['Amrit Mahal', 'Khillari'], [Language.HI]: ['अमृत महल', 'खिल्लारी'] }
    },
    {
        id: 12, name: 'Jersey', milkQuality: { fat: '4.8-5.5%', protein: '3.6-4.0%' }, location: 'Global / Popular in India', ranking: 5,
        suitability: { [Language.EN]: 'Excellent for high-fat milk (A2), small body size, efficient converter of feed to milk.', [Language.HI]: 'उच्च वसा वाले दूध (A2) के लिए उत्कृष्ट, छोटा शरीर, चारे को दूध में बदलने में कुशल।' },
        monthlyExpense: { [Language.EN]: '₹4,000 - ₹5,500 per animal.', [Language.HI]: '₹4,000 - ₹5,500 प्रति पशु।' },
        breedingSeason: { [Language.EN]: 'Year-round, early maturity.', [Language.HI]: 'साल भर, जल्दी परिपक्वता।' },
        matingSuggestions: { [Language.EN]: ['Holstein Friesian (for volume)', 'Local breeds (for hardiness)'], [Language.HI]: ['होलस्टीन फ्रीजियन (मात्रा के लिए)', 'स्थानीय नस्लें (कठोरता के लिए)'] }
    },
    {
        id: 13, name: 'Holstein Friesian', milkQuality: { fat: '3.5-4.0%', protein: '3.0-3.3%' }, location: 'Global / Punjab, UP', ranking: 5,
        suitability: { [Language.EN]: 'Highest milk production volume in the world. Requires intensive management.', [Language.HI]: 'दुनिया में सबसे ज्यादा दूध उत्पादन। गहन प्रबंधन की आवश्यकता है।' },
        monthlyExpense: { [Language.EN]: '₹5,000 - ₹7,000 per animal (high feed intake).', [Language.HI]: '₹5,000 - ₹7,000 प्रति पशु (उच्च चारा सेवन)।' },
        breedingSeason: { [Language.EN]: 'Year-round, adaptable to different climates with proper care.', [Language.HI]: 'उचित देखभाल के साथ साल भर, विभिन्न जलवायु के अनुकूल।' },
        matingSuggestions: { [Language.EN]: ['Jersey (for fat content)', 'Sahiwal (for heat tolerance)'], [Language.HI]: ['जर्सी (वसा सामग्री के लिए)', 'साहीवाल (गर्मी सहनशीलता के लिए)'] }
    }
];

export const MOCK_SCHEMES_DATA: SchemeData[] = [
  {
    id: 1,
    name: {
      [Language.EN]: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
      [Language.HI]: 'प्रधानमंत्री किसान सम्मान निधि (पीएम-किसान)',
      [Language.MR]: 'प्रधानमंत्री किसान सन्मान निधी (पीएम-किसान)',
      [Language.GU]: 'પ્રધાનમંત્રી કિસાન સન્માન નિધિ (પીએમ-કિસાન)',
      [Language.TE]: 'ప్రధాన మంత్రి కిసాన్ సమ్మాన్ నిధి (పిఎం-కిసాన్)',
      [Language.ML]: 'പ്രധാനമന്ത്രി കിസാൻ സമ്മാൻ നിധി (പിഎം-കിസാൻ)',
      [Language.TA]: 'பிரதான் மந்திரி கிசான் சம்மான் நிதி (பிஎம்-கிசான்)',
      [Language.KN]: 'ಪ್ರಧಾನ ಮಂತ್ರಿ ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ (ಪಿಎಂ-ಕಿಸಾನ್)',
    },
    description: {
      [Language.EN]: 'A central sector scheme with 100% funding from the Government of India. It provides income support to all landholding farmer families in the country to supplement their financial needs.',
      [Language.HI]: 'यह भारत सरकार से 100% वित्त पोषण के साथ एक केंद्रीय क्षेत्र की योजना है। यह देश के सभी भूमिधारक किसान परिवारों को उनकी वित्तीय जरूरतों को पूरा करने के लिए आय सहायता प्रदान करती है।',
      [Language.MR]: 'ही भारत सरकारकडून १००% निधीसह एक केंद्रीय क्षेत्र योजना आहे. देशातील सर्व जमीनधारक शेतकरी कुटुंबांना त्यांच्या आर्थिक गरजा पूर्ण करण्यासाठी उत्पन्न समर्थन प्रदान करते.',
      [Language.GU]: 'આ ભારત સરકાર પાસેથી 100% ભંડોળ સાથેની કેન્દ્રીય ક્ષેત્રની યોજના છે. તે દેશના તમામ જમીનધારક ખેડૂત પરિવારોને તેમની નાણાકીય જરૂરિયાતોને પહોંચી વળવા માટે આવક સહાય પૂરી પાડે છે.',
      [Language.TE]: 'ఇది భారత ప్రభుత్వం నుండి 100% నిధులతో కూడిన కేంద్ర రంగ పథకం. ఇది దేశంలోని భూస్వామ్య రైతు కుటుంబాలందరికీ వారి ఆర్థిక అవసరాలను తీర్చడానికి ఆదాయ మద్దతును అందిస్తుంది.',
      [Language.ML]: 'ഇന്ത്യൻ ഗവൺമെന്റിൽ നിന്ന് 100% ഫണ്ടിംഗോടുകൂടിയ ഒരു കേന്ദ്രമേഖലാ പദ്ധതിയാണിത്. രാജ്യത്തെ എല്ലാ ഭൂവുടമ കർഷക കുടുംബങ്ങൾക്കും അവരുടെ സാമ്പത്തിക ആവശ്യങ്ങൾ നിറവേറ്റുന്നതിനായി വരുമാന പിന്തുണ നൽകുന്നു.',
      [Language.TA]: 'இது இந்திய அரசிடமிருந்து 100% நிதியுதவியுடன் கூடிய ஒரு மத்திய துறை திட்டமாகும். இது நாட்டின் அனைத்து நில உரிமையாளர் விவசாயி குடும்பங்களுக்கும் அவர்களின் நிதித் தேவைகளை பூர்த்தி செய்ய வருமான ஆதரவை வழங்குகிறது.',
      [Language.KN]: 'ಇದು ಭಾರತ ಸರ್ಕಾರದಿಂದ 100% ನಿಧಿಯೊಂದಿಗೆ ಕೇಂದ್ರ ವಲಯದ ಯೋಜನೆಯಾಗಿದೆ. ಇದು ದೇಶದ ಎಲ್ಲಾ ಭೂಮಾಲೀಕ ರೈತ ಕುಟುಂಬಗಳಿಗೆ ಅವರ ಆರ್ಥಿಕ ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸಲು ಆದಾಯ ಬೆಂಬಲವನ್ನು ಒದಗಿಸುತ್ತದೆ.',
    },
    eligibility: {
      [Language.EN]: ['All landholding farmer families.', 'Excludes institutional landholders, farmer families with constitutional posts, etc.'],
      [Language.HI]: ['सभी भूमिधारक किसान परिवार।', 'संस्थागत भूमिधारकों, संवैधानिक पदों वाले किसान परिवारों आदि को छोड़कर।'],
      [Language.MR]: ['सर्व जमीनधारक शेतकरी कुटुंबे.', 'संस्थात्मक जमीनधारक, घटनात्मक पदे असलेली शेतकरी कुटुंबे इत्यादी वगळून.'],
      [Language.GU]: ['તમામ જમીનધારક ખેડૂત પરિવારો.', 'સંસ્થાકીય જમીનધારકો, બંધારણીય હોદ્દા ધરાવતા ખેડૂત પરિવારો વગેરેને બાકાત રાખે છે.'],
      [Language.TE]: ['భూస్వామ్య రైతు కుటుంబాలన్నీ.', 'సంస్థాగత భూస్వాములు, రాజ్యాంగ పదవులతో ఉన్న రైతు కుటుంబాలు మొదలైనవాటిని మినహాయిస్తుంది.'],
      [Language.ML]: ['എല്ലാ ഭൂവുടമ കർഷക കുടുംബങ്ങളും.', 'സ്ഥാപനപരമായ ഭൂവുടമകൾ, ഭരണഘടനാപരമായ തസ്തികകളുള്ള കർഷക കുടുംബങ്ങൾ മുതലായവയെ ഒഴിവാക്കുന്നു.'],
      [Language.TA]: ['அனைத்து நில உரிமையாளர் விவசாயி குடும்பங்கள்.', 'நிறுவன நில உரிமையாளர்கள், அரசியலமைப்பு பதவிகளைக் கொண்ட விவசாயி குடும்பங்கள் போன்றவற்றை விலக்குகிறது.'],
      [Language.KN]: ['ಎಲ್ಲಾ ಭೂಮಾಲೀಕ ರೈತ ಕುಟುಂಬಗಳು.', 'ಸಾಂಸ್ಥಿಕ ಭೂಮಾಲೀಕರು, ಸಾಂವಿಧಾನಿಕ ಹುದ್ದೆಗಳನ್ನು ಹೊಂದಿರುವ ರೈತ ಕುಟುಂಬಗಳು ಇತ್ಯಾದಿಗಳನ್ನು ಹೊರತುಪಡಿಸಿ.'],
    },
    link: 'https://pmkisan.gov.in/',
  },
  {
    id: 2,
    name: {
      [Language.EN]: 'National Livestock Mission',
      [Language.HI]: 'राष्ट्रीय पशुधन मिशन',
      [Language.MR]: 'राष्ट्रीय पशुधन अभियान',
      [Language.GU]: 'રાષ્ટ્રીય પશુધન મિશન',
      [Language.TE]: 'జాతీయ పశుసంపద మిషన్',
      [Language.ML]: 'ദേശീയ കന്നുകാലി മിഷൻ',
      [Language.TA]: 'தேசிய கால்நடை இயக்கம்',
      [Language.KN]: 'ರಾಷ್ಟ್ರೀಯ ಜಾನುವಾರು ಮಿಷನ್',
    },
    description: {
      [Language.EN]: 'Aims to ensure quantitative and qualitative improvement in livestock production systems and capacity building of all stakeholders. Focuses on entrepreneurship development and breed improvement.',
      [Language.HI]: 'इसका उद्देश्य पशुधन उत्पादन प्रणालियों में मात्रात्मक और गुणात्मक सुधार सुनिश्चित करना और सभी हितधारकों की क्षमता का निर्माण करना है। उद्यमिता विकास और नस्ल सुधार पर ध्यान केंद्रित करता है।',
      [Language.MR]: 'पशुधन उत्पादन प्रणालीमध्ये संख्यात्मक आणि गुणात्मक सुधारणा सुनिश्चित करणे आणि सर्व भागधारकांची क्षमता वाढवणे हे याचे उद्दिष्ट आहे. उद्योजकता विकास आणि जाती सुधारण्यावर लक्ष केंद्रित करते.',
      [Language.GU]: 'પશુધન ઉત્પાદન પ્રણાલીઓમાં માત્રાત્મક અને ગુણાત્મક સુધારણા સુનિશ્ચિત કરવાનો અને તમામ હિતધારકોની ક્ષમતા નિર્માણ કરવાનો હેતુ છે. ઉદ્યોગસાહસિકતા વિકાસ અને જાતિ સુધારણા પર ધ્યાન કેન્દ્રિત કરે છે.',
      [Language.TE]: 'పశుసంపద ఉత్పత్తి వ్యవస్థలలో పరిమాణాత్మక మరియు గుణాత్మక అభివృద్ధిని నిర్ధారించడం మరియు అన్ని వాటాదారుల సామర్థ్యాన్ని పెంపొందించడం లక్ష్యంగా పెట్టుకుంది. వ్యవస్థాపకత అభివృద్ధి మరియు జాతి అభివృద్ధిపై దృష్టి పెడుతుంది.',
      [Language.ML]: 'കന്നുകാലി ഉത്പാദന സംവിധാനങ്ങളിൽ അളവിലും ഗുണത്തിലും പുരോഗതി ഉറപ്പാക്കുക, എല്ലാ പങ്കാളികളുടെയും ശേഷി വർദ്ധിപ്പിക്കുക എന്നിവ ലക്ഷ്യമിടുന്നു. സംരംഭകത്വ വികസനത്തിലും ഇനങ്ങളുടെ മെച്ചപ്പെടുത്തലിലും ശ്രദ്ധ കേന്ദ്രീകരിക്കുന്നു.',
      [Language.TA]: 'கால்நடை உற்பத்தி அமைப்புகளில் அளவு மற்றும் தரமான மேம்பாட்டை உறுதி செய்வதையும், அனைத்து பங்குதாரர்களின் திறனை வளர்ப்பதையும் நோக்கமாகக் கொண்டுள்ளது. தொழில்முனைவோர் மேம்பாடு மற்றும் இன மேம்பாட்டில் கவனம் செலுத்துகிறது.',
      [Language.KN]: 'ಜಾನುವಾರು ಉತ್ಪಾದನಾ ವ್ಯವಸ್ಥೆಗಳಲ್ಲಿ ಪರಿಮಾಣಾತ್ಮಕ ಮತ್ತು ಗುಣಾತ್ಮಕ ಸುಧಾರಣೆಯನ್ನು ಖಚಿತಪಡಿಸುವುದು ಮತ್ತು ಎಲ್ಲಾ ಮಧ್ಯಸ್ಥಗಾರರ ಸಾಮರ್ಥ್ಯವನ್ನು ನಿರ್ಮಿಸುವುದು ಇದರ ಗುರಿಯಾಗಿದೆ. ಉದ್ಯಮಶೀಲತೆ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ತಳಿ ಸುಧಾರಣೆಯ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ.',
    },
    eligibility: {
      [Language.EN]: ['Individuals, Self Help Groups (SHG), Farmer Producer Organizations (FPO).', 'Varies by sub-mission components (e.g., poultry, sheep, goat, piggery).'],
      [Language.HI]: ['व्यक्ति, स्वयं सहायता समूह (एसएचजी), किसान उत्पादक संगठन (एफपीओ)।', 'उप-मिशन घटकों (जैसे, मुर्गी पालन, भेड़, बकरी, सुअर पालन) के अनुसार भिन्न होता है।'],
      [Language.MR]: ['व्यक्ती, बचत गट (SHG), शेतकरी उत्पादक संस्था (FPO).', 'उप-अभियान घटकांनुसार बदलते (उदा. पोल्ट्री, मेंढी, शेळी, डुक्कर पालन).'],
      [Language.GU]: ['વ્યક્તિઓ, સ્વ-સહાય જૂથો (SHG), ખેડૂત ઉત્પાદક સંગઠનો (FPO).', 'પેટા-મિશન ઘટકો (દા.ત. મરઘાં, ઘેટાં, બકરી, ડુક્કર) દ્વારા બદલાય છે.'],
      [Language.TE]: ['వ్యక్తులు, స్వయం సహాయక బృందాలు (SHG), రైతు ఉత్పత్తిదారుల సంస్థలు (FPO).', 'ఉప-మిషన్ భాగాల ద్వారా మారుతుంది (ఉదా. పౌల్ట్రీ, గొర్రెలు, మేక, పందుల పెంపకం).'],
      [Language.ML]: ['വ്യക്തികൾ, സ്വയം സഹായ സംഘങ്ങൾ (SHG), കർഷക ഉത്പാദക സംഘടനകൾ (FPO).', 'ഉപ-ദൗത്യ ഘടകങ്ങൾ അനുസരിച്ച് വ്യത്യാസപ്പെടുന്നു (ഉദാ. കോഴിവളർത്തൽ, ആട്, പന്നി വളർത്തൽ).'],
      [Language.TA]: ['தனிநபர்கள், சுய உதவி குழுக்கள் (SHG), உழவர் உற்பத்தியாளர் அமைப்புகள் (FPO).', 'துணைப் பணி கூறுகளைப் பொறுத்து மாறுபடும் (எ.கா. கோழி, ஆடு, செம்மறி, பன்றி வளர்ப்பு).'],
      [Language.KN]: ['ವ್ಯಕ್ತಿಗಳು, ಸ್ವ-ಸಹಾಯ ಗುಂಪುಗಳು (SHG), ರೈತ ಉತ್ಪಾದಕ ಸಂಸ್ಥೆಗಳು (FPO).', 'ಉಪ-ಮಿಷನ್ ಘಟಕಗಳ ಪ್ರಕಾರ ಬದಲಾಗುತ್ತದೆ (ಉದಾ. ಕೋಳಿ, ಕುರಿ, ಮೇಕೆ, ಹಂದಿ ಸಾಕಾಣಿಕೆ).'],
    },
    link: 'https://dahd.nic.in/schemes/programmes/national-livestock-mission',
  },
  {
    id: 3,
    name: {
      [Language.EN]: 'Kisan Credit Card (KCC) Scheme',
      [Language.HI]: 'किसान क्रेडिट कार्ड (केसीसी) योजना',
      [Language.MR]: 'किसान क्रेडिट कार्ड (केसीसी) योजना',
      [Language.GU]: 'કિસાન ક્રેડિટ કાર્ડ (KCC) યોજના',
      [Language.TE]: 'కిసాన్ క్రెడిట్ కార్డ్ (కెసిసి) పథకం',
      [Language.ML]: 'കിസാൻ ക്രെഡിറ്റ് കാർഡ് (കെസിസി) പദ്ധതി',
      [Language.TA]: 'கிசான் கிரெடிட் கார்டு (கேசிசி) திட்டம்',
      [Language.KN]: 'ಕಿಸಾನ್ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್ (ಕೆಸಿಸಿ) ಯೋಜನೆ',
    },
    description: {
      [Language.EN]: 'Provides farmers with timely access to credit for their cultivation and other needs. Animal husbandry and fisheries farmers are also included to help them with their working capital requirements.',
      [Language.HI]: 'किसानों को उनकी खेती और अन्य जरूरतों के लिए समय पर ऋण उपलब्ध कराता है। पशुपालन और मत्स्य पालन करने वाले किसानों को भी उनकी कार्यशील पूंजी की आवश्यकताओं में मदद करने के लिए शामिल किया गया है।',
      [Language.MR]: 'शेतकऱ्यांना त्यांच्या शेती आणि इतर गरजांसाठी वेळेवर पतपुरवठा करते. पशुसंवर्धन आणि मत्स्यपालन करणाऱ्या शेतकऱ्यांना त्यांच्या खेळत्या भांडवलाच्या गरजांसाठी मदत करण्यासाठी समाविष्ट केले आहे.',
      [Language.GU]: 'ખેડૂતોને તેમની ખેતી અને અન્ય જરૂરિયાતો માટે સમયસર ધિરાણ પૂરું પાડે છે. પશુપાલન અને મત્સ્યોદ્યોગના ખેડૂતોને પણ તેમની કાર્યકારી મૂડીની જરૂરિયાતોમાં મદદ કરવા માટે સમાવવામાં આવ્યા છે.',
      [Language.TE]: 'రైతులకు వారి సాగు మరియు ఇతర అవసరాల కోసం సకాలంలో రుణాన్ని అందిస్తుంది. పశుసంవర్ధక మరియు మత్స్య రైతులు కూడా వారి వర్కింగ్ క్యాపిటల్ అవసరాలకు సహాయం చేయడానికి చేర్చబడ్డారు.',
      [Language.ML]: 'കർഷകർക്ക് അവരുടെ കൃഷിക്കും മറ്റ് ആവശ്യങ്ങൾക്കും സമയബന്ധിതമായി വായ്പ നൽകുന്നു. മൃഗസംരക്ഷണ, മത്സ്യബന്ധന കർഷകരെയും അവരുടെ പ്രവർത്തന മൂലധന ആവശ്യകതകൾക്ക് സഹായിക്കുന്നതിനായി ഉൾപ്പെടുത്തിയിട്ടുണ്ട്.',
      [Language.TA]: 'விவசாயிகளுக்கு அவர்களின் சாகுபடி மற்றும் பிற தேவைகளுக்கு சரியான நேரத்தில் கடன் அணுகலை வழங்குகிறது. கால்நடை வளர்ப்பு மற்றும் மீன்வள விவசாயிகளும் அவர்களின் செயல்பாட்டு மூலதனத் தேவைகளுக்கு உதவ சேர்க்கப்பட்டுள்ளனர்.',
      [Language.KN]: 'ರೈತರಿಗೆ ಅವರ ಕೃಷಿ ಮತ್ತು ಇತರ ಅಗತ್ಯಗಳಿಗಾಗಿ ಸಮಯೋಚಿತ ಸಾಲ ಸೌಲಭ್ಯವನ್ನು ಒದಗಿಸುತ್ತದೆ. ಪಶುಸಂಗೋಪನೆ ಮತ್ತು ಮೀನುಗಾರಿಕೆ ರೈತರನ್ನು ಅವರ ಕಾರ್ಯನಿರತ ಬಂಡವಾಳದ ಅವಶ್ಯಕತೆಗಳಿಗೆ ಸಹಾಯ ಮಾಡಲು ಸೇರಿಸಲಾಗಿದೆ.',
    },
    eligibility: {
      [Language.EN]: ['All farmers - individuals/joint borrowers who are owner cultivators.', 'Tenant farmers, oral lessees & sharecroppers.', 'SHGs or Joint Liability Groups of farmers.'],
      [Language.HI]: ['सभी किसान - व्यक्ति/संयुक्त उधारकर्ता जो मालिक कृषक हैं।', 'किरायेदार किसान, मौखिक पट्टेदार और बटाईदार।', 'किसानों के स्वयं सहायता समूह या संयुक्त देयતા समूह।'],
      [Language.MR]: ['सर्व शेतकरी - व्यक्ती/संयुक्त कर्जदार जे मालक शेतकरी आहेत.', 'भाडेकरू शेतकरी, तोंडी भाडेपट्टेदार आणि वाटेकरी.', 'शेतकऱ्यांचे बचत गट किंवा संयुक्त दायित्व गट.'],
      [Language.GU]: ['બધા ખેડૂતો - વ્યક્તિગત/સંયુક્ત ઉધાર લેનારા જે માલિક ખેડૂત છે.', 'ભાડૂત ખેડૂતો, મૌખિક પટેદારો અને ભાગીદારો.', 'ખેડૂતોના SHG અથવા સંયુક્ત જવાબદારી જૂથો.'],
      [Language.TE]: ['రైతులందరూ - యజమాని సాగుదారులు అయిన వ్యక్తులు/ఉమ్మడి రుణగ్రహీతలు.', 'కౌలు రైతులు, మౌఖిక లీజుదారులు & వాటాదారులు.', 'రైతుల SHGలు లేదా ఉమ్మడి బాధ్యత సమూహాలు.'],
      [Language.ML]: ['എല്ലാ കർഷകരും - ഉടമസ്ഥരായ വ്യക്തിഗത/സംയുക്ത വായ്പക്കാർ.', 'കുടിയാൻ കർഷകർ, വാക്കാലുള്ള പാട്ടക്കാർ, പങ്കു കൃഷിക്കാർ.', 'കർഷകരുടെ സ്വയം സഹായ സംഘങ്ങൾ അല്ലെങ്കിൽ സംയുക്ത ബാധ്യതാ ഗ്രൂപ്പുകൾ.'],
      [Language.TA]: ['அனைத்து விவசாயிகள் - உரிமையாளர் சாகுபடியாளர்களான தனிநபர்கள்/கூட்டு கடன் வாங்குபவர்கள்.', 'குத்தகை விவசாயிகள், வாய்மொழி குத்தகைதாரர்கள் மற்றும் பங்குதாரர்கள்.', 'விவசாயிகளின் சுய உதவி குழுக்கள் அல்லது கூட்டு பொறுப்புக் குழுக்கள்.'],
      [Language.KN]: ['ಎಲ್ಲಾ ರೈತರು - ಮಾಲೀಕ ಕೃಷಿಕರಾಗಿರುವ ವ್ಯಕ್ತಿಗಳು/ಜಂಟಿ ಸಾಲಗಾರರು.', 'ಬಾಡಿಗೆದಾರ ರೈತರು, ಮೌಖಿಕ ಗುತ್ತಿಗೆದಾರರು ಮತ್ತು ಪಾಲುದಾರರು.', 'ರೈತರ SHGಗಳು ಅಥವಾ ಜಂಟಿ ಹೊಣೆಗಾರಿಕೆ ಗುಂಪುಗಳು.'],
    },
    link: 'https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=11623&Mode=0',
  },
];